"""Generate MODEL_CARD.md from the saved result files, so its numbers can't drift from the real runs.

Called by `python -m src.model.train` (test results "pending") and again by
`python -m src.model.final_test` (test and recent results filled in).
"""

import json
from pathlib import Path

from src.config import (
    FINAL_TEST_REPORT_JSON,
    MODEL_CARD_PATH,
    MODEL_METADATA_PATH,
    SPLIT_YEARS,
    VALIDATION_REPORT_JSON,
)
from src.dataset.audit import AUDIT_JSON
from src.model.report import band_rows, scores_rows, years


def read_json(path: Path) -> dict | None:
    """Parsed JSON, or None if the file doesn't exist yet."""
    return json.loads(path.read_text(encoding="utf-8")) if path.exists() else None


def model_card_markdown(meta: dict, val: dict, audit: dict, final: dict | None) -> str:
    """The model card as Markdown."""
    cleaning = audit["cleaning"]
    best_single = max(audit["features"], key=lambda f: f["auc_train"])
    caution = [f["name"] for f in meta["features"] if f["group"] == "caution"]
    n_strict = sum(f["group"] == "strict" for f in meta["features"])
    leak = {m["column"]: m["auc_train"] for m in audit["measured_leaks"]}
    lines = [
        "# Model card – TrialScout trial termination risk",
        "",
        "Generated by `src/model/card.py` from `models/model_metadata.json`, `reports/model_validation.json`, "
        "`data/LEAKAGE_AUDIT.json` and (once run) `reports/model_final_test.json`. Do not edit by hand.",
        "",
        "## What it does",
        "",
        "Given what is known about an interventional clinical trial **when it starts** (design, sponsor type, "
        "eligibility, disease area...), it estimates the probability that the trial ends as TERMINATED rather "
        "than COMPLETED, and turns it into a Low / Medium / High risk band.",
        "",
        "**Intended use:** a portfolio and learning project; showing patterns in public registry data next to "
        "search results. **Not for:** decisions about real trials, patients, funding or investments.",
        "",
        f"> {meta['disclaimer']}",
        "",
        "## Data",
        "",
        f"- Source: ClinicalTrials.gov API v2, interventional trials that started {SPLIT_YEARS['train'][0]}–"
        f"{SPLIT_YEARS['recent'][1]} and ended COMPLETED (label 0) or TERMINATED (label 1). WITHDRAWN trials "
        "(never enrolled anyone) and trials with no final outcome are not included.",
        f"- {cleaning['late_registration']['dropped']} trials registered only after they ended were dropped "
        f"({cleaning['late_registration']['terminated_pct_among_dropped']}% of them terminated): no prediction "
        "at start was ever possible for them.",
        f"- {cleaning['covid_terminated']['flagged']} trials terminated because of COVID-19 (keyword match on "
        "`why_stopped`, used only for this flag). Data version used for this model: "
        f"**`{meta['data_version']}`** (`main` leaves those trials out; `with_covid` keeps them).",
        f"- Split by start year: trained on {years('train')} ({meta['train_rows']} trials), tuned and calibrated "
        f"on {years('val')}, tested once on {years('test')}; {years('recent')} reported separately.",
        "",
        "## Features",
        "",
        f"{len(meta['features'])} features: {n_strict} known at trial start, plus {len(caution)} *caution* "
        "features." if caution else f"{len(meta['features'])} features, all known at trial start (strict set).",
        "",
    ]
    if caution:
        lines += ["**Caution features** (planned at start, but the registry keeps only the latest version, so "
                  "they may have been edited while the trial ran):", "", *[f"- `{c}`" for c in caution], ""]
    lines += [
        "Deliberately **not** used (see `data/LEAKAGE_AUDIT.md`): `why_stopped`, completion dates, results, "
        f"`enrollment_count` (holds the *actual* final number; alone it would score AUC {leak.get('enrollment_count')} "
        "on the training years, and live trials only have a planned number), sponsor names, start year, and "
        "the FDA-regulated fields (their meaning changed with a 2017 rule).",
        "",
        "## Model",
        "",
        f"- `{meta['model']}` with settings {meta['params']}, inside a scikit-learn pipeline (one-hot categories, "
        "median-filled and scaled numbers) fitted on the training years only.",
        f"- Calibration: `{meta['calibration_method']}`, fitted on {years('val')}.",
        f"- Risk bands from the {years('val')} base rate b = {meta['risk_bands']['validation_base_rate']}: "
        f"Low p < {meta['risk_bands']['cutoffs']['low_max']}, Medium up to {meta['risk_bands']['cutoffs']['high_min']}, "
        "High above.",
        f"- Yes/no threshold for precision/recall: {meta['f1_threshold']} (best F1 on validation).",
        f"- File: `models/{meta['file']}`, {meta['size_mb']} MB; scikit-learn {meta['library_versions']['scikit-learn']}, "
        f"LightGBM {meta['library_versions']['lightgbm']}.",
        "",
        f"## Validation results ({years('val')}, calibrated out-of-fold)",
        "",
        *scores_rows([("Dummy (always completed)", val["dummy_val_main"]), (meta["model"], val["val_main"])]),
        "",
        *band_rows(val["bands_val"], val["band_cutoffs"]),
        "",
        f"## Test results ({years('test')}, used once)",
        "",
    ]
    if final:
        for version, part in final["test"].items():
            lines += [f"Rows `{version}` ({part['rows']} trials):", "",
                      *scores_rows([("Dummy (always completed)", part["dummy"]), (meta["model"], part["model"])]),
                      "", *band_rows(part["bands"], final["band_cutoffs"]), ""]
        lines += [f"## Recent trials ({years('recent')}), reported separately", "", final["censoring_note"], ""]
        for version, part in final["recent"].items():
            lines += [f"Rows `{version}` ({part['rows']} trials): PR-AUC {part['model']['pr_auc']} "
                      f"(dummy {part['dummy']['pr_auc']}), ROC-AUC {part['model']['roc_auc']}.", ""]
    else:
        lines += ["**Pending.** The final test runs once, after the chosen model is approved "
                  "(`python -m src.model.final_test --approved`).", ""]
    lines += [
        "## Limitations",
        "",
        f"- **Moderate predictive power.** Termination depends a lot on things not in the registry at the start "
        f"(funding changes, recruitment problems, safety findings, business decisions). No single start-time "
        f"feature separates the classes well: the best one alone reaches AUC {best_single['auc_train']} "
        f"(`{best_single['feature']}`).",
        "- **Latest record, not the start-time record.** The registry keeps only the current version of each "
        "trial, so even \"known at start\" fields may have been edited later.",
        f"- **Right-censoring.** Recent start years are missing their long-running trials, so {years('recent')} "
        "results are a stress test, not the main result.",
        "- **Time and shocks.** Trained on 2010–2016 trials; practices and rules change (e.g. the 2017 rule "
        "change, COVID-19). Performance on future trials may differ.",
        "- **Registry coverage.** Only trials registered on ClinicalTrials.gov (a US registry); trials listed "
        "only in other countries' registries are not included.",
        "- **Association, not cause.** A feature linked to higher risk does not make a trial fail.",
        "- **Label meaning.** TERMINATED covers very different reasons (safety, futility, funding, slow "
        "recruitment, business). The model does not say which.",
    ]
    return "\n".join(lines) + "\n"


def write_model_card(path: Path = MODEL_CARD_PATH) -> Path:
    """Write MODEL_CARD.md from the current result files. Returns its path."""
    meta, val = read_json(MODEL_METADATA_PATH), read_json(VALIDATION_REPORT_JSON)
    audit, final = read_json(AUDIT_JSON), read_json(FINAL_TEST_REPORT_JSON)
    if not (meta and val and audit):
        raise FileNotFoundError("Model metadata, validation report or leakage audit missing; "
                                "run python -m src.model.train first.")
    path.write_text(model_card_markdown(meta, val, audit, final), encoding="utf-8")
    return path
