"""Render the Phase 9 result files (JSON) as readable Markdown. Nothing here computes a model score."""

import json
from pathlib import Path

from src.config import FINAL_TEST_REPORT_MD, SPLIT_YEARS, VALIDATION_REPORT_MD
from src.dataset.audit import AUDIT_JSON


def censoring_note(audit_path: Path = AUDIT_JSON) -> str:
    """The censoring warning for the recent set, with the still-running shares from the Phase 8 audit."""
    first, last = SPLIT_YEARS["recent"]
    rows = json.loads(audit_path.read_text(encoding="utf-8"))["censoring"]
    running = ", ".join(f"{r['still_running_pct']}% of {r['start_year']}" for r in rows
                        if first <= r["start_year"] <= last)
    return (f"**Censoring note:** many trials that started in {first}–{last} are still running ({running} "
            "interventional trials, Phase 8 API check), and the missing ones are mostly long trials. So this "
            "set over-represents short trials, and these years were also hit hardest by COVID-19. Treat these "
            "numbers as a stress test, not as the main result.")


def years(part: str) -> str:
    """'2010–2016' style label for a split."""
    first, last = SPLIT_YEARS[part]
    return f"{first}" if first == last else f"{first}–{last}"


def scores_rows(named: list[tuple[str, dict]]) -> list[str]:
    """Table rows of ranking + threshold scores for (name, all_scores dict) pairs."""
    lines = ["| Model | PR-AUC | ROC-AUC | Brier | Precision | Recall | F1 | Accuracy | TN | FP | FN | TP |",
             "|---|---|---|---|---|---|---|---|---|---|---|---|"]
    for name, s in named:
        t, cm = s["at_threshold"], s["at_threshold"]["confusion_matrix"]
        lines.append(f"| {name} | {s['pr_auc']} | {s['roc_auc']} | {s['brier']} | {t['precision']} | "
                     f"{t['recall']} | {t['f1']} | {t['accuracy']} | {cm['tn']} | {cm['fp']} | {cm['fn']} | {cm['tp']} |")
    return lines


def band_rows(bands: list[dict], cutoffs: dict) -> list[str]:
    """Table of the risk bands."""
    ranges = {"Low": f"p < {cutoffs['low_max']}", "Medium": f"{cutoffs['low_max']} ≤ p < {cutoffs['high_min']}",
              "High": f"p ≥ {cutoffs['high_min']}"}
    lines = ["| Band | Probability | Trials | Share | Terminated | Actual terminated rate |", "|---|---|---|---|---|---|"]
    for b in bands:
        rate = "—" if b["actual_rate_pct"] is None else f"{b['actual_rate_pct']}%"
        lines.append(f"| {b['band']} | {ranges[b['band']]} | {b['trials']} | {b['share_pct']}% | "
                     f"{b['terminated']} | {rate} |")
    return lines


def reliability_rows(raw: list[dict], calibrated: list[dict]) -> list[str]:
    """Side-by-side reliability tables (raw vs calibrated), one row per bin."""
    lines = ["| Bin | Trials | Raw: mean predicted | Raw: actual | Calibrated: mean predicted | Calibrated: actual |",
             "|---|---|---|---|---|---|"]
    for i, (r, c) in enumerate(zip(raw, calibrated), start=1):
        lines.append(f"| {i} | {r['trials']} | {r['mean_predicted']} | {r['actual_rate']} | "
                     f"{c['mean_predicted']} | {c['actual_rate']} |")
    return lines


def validation_markdown(r: dict) -> str:
    """The validation report as Markdown."""
    c, check, cal = r["chosen"], r["band_check"], r["calibration"]
    dummy = r["dummy_val_main"]
    lines = [
        "# Model validation report – Phase 9",
        "",
        f"Generated by `python -m src.model.train` on {r['generated_at']} (runtime {r['runtime_minutes']} min). "
        "Do not edit by hand; numbers are also in `model_validation.json`.",
        "",
        f"Every model is trained on start years {years('train')} and scored on {years('val')} "
        f"({r['validation_rows']['main']} main validation rows; {r['validation_rows']['with_covid']} with COVID-"
        f"terminated trials). **The {years('test')} test set was not used.**",
        "",
        "## Summary",
        "",
        f"- Selection rule: {r['selection_rule']}.",
        f"- **Chosen: `{c['model']}`** {c['params']}, data `{c['data_version']}`, features `{c['feature_set']}`.",
        f"- Validation PR-AUC **{r['val_main']['pr_auc']}** vs {dummy['pr_auc']} for the dummy (= share of "
        f"terminated trials); ROC-AUC **{r['val_main']['roc_auc']}** vs 0.5.",
        f"- Calibration: `{cal['method']}` (lowest cross-validated Brier score).",
        f"- Risk-band check: largest band `{check['largest_band']}` holds {check['largest_share_pct']}% of "
        f"validation trials (limit {check['max_allowed_pct']}%): **{'OK' if check['ok'] else 'NOT OK'}**.",
        f"- Model saved: **{'yes' if r['saved'] else 'no'}**"
        + (f" ({r['model_size_mb']} MB, sha256 `{r['model_sha256'][:12]}…`)." if r["saved"] else "."),
        "",
        "## 1. Best setting per data version, feature set and model",
        "",
        "PR-AUC and ROC-AUC on the main validation rows (the selection basis), then on the with_covid "
        "validation rows. Precision/recall/F1 here use each run's own best-F1 threshold on validation, "
        "so they are slightly optimistic; section 3 has the chosen model's honest numbers.",
        "",
        "| Data | Features | Model | Best setting | PR-AUC | ROC-AUC | Brier | Precision | Recall | F1 | "
        "PR-AUC (with_covid val) | ROC-AUC (with_covid val) | Fit s | Size MB |",
        "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|",
    ]
    for b in r["best_per_group"]:
        t = b["val_main_at_best_f1"]
        lines.append(f"| {b['data_version']} | {b['feature_set']} | {b['model']} | {b['params']} | "
                     f"{b['val_main']['pr_auc']} | {b['val_main']['roc_auc']} | {b['val_main']['brier']} | "
                     f"{t['precision']} | {t['recall']} | {t['f1']} | {b['val_with_covid']['pr_auc']} | "
                     f"{b['val_with_covid']['roc_auc']} | {b['fit_seconds']} | {b['size_mb']} |")

    lines += ["", "## 2. Comparisons (best PR-AUC on the main validation rows)", "",
              "| Data version | strict | strict+caution |", "|---|---|---|"]
    best_of = {}
    for b in r["best_per_group"]:
        if b["model"] == "dummy":
            continue
        key = (b["data_version"], b["feature_set"])
        best_of[key] = max(best_of.get(key, 0), b["val_main"]["pr_auc"])
    for version in sorted({k[0] for k in best_of}):
        lines.append(f"| {version} | {best_of.get((version, 'strict'), '—')} | "
                     f"{best_of.get((version, 'strict+caution'), '—')} |")

    lines += [
        "", "## 3. Chosen model on validation (calibrated)", "",
        f"Probabilities are calibrated **out-of-fold** within {years('val')}, so each trial's probability comes "
        f"from a calibrator not fitted on it. Threshold for precision/recall/F1: **{r['threshold']:.4f}** "
        "(best F1 on validation; it is applied unchanged to the test set later). The dummy always predicts "
        "\"completed\".", "",
        *scores_rows([("Dummy (always completed)", dummy), (f"{c['model']} – main validation", r["val_main"]),
                      (f"{c['model']} – with_covid validation", r["val_with_covid"])]),
        "",
        "## 4. Calibration", "",
        "Cross-validated Brier score within validation (lower is better): "
        + ", ".join(f"`{m}` {v}" for m, v in cal["brier_cv_by_method"].items()) + ".", "",
        f"Reliability table ({len(cal['reliability_raw'])} bins with equal numbers of trials): for a "
        "well-calibrated model, mean predicted ≈ actual rate.", "",
        *reliability_rows(cal["reliability_raw"], cal["reliability_calibrated"]),
        "",
        "## 5. Risk bands (validation)", "",
        f"Base rate b = {r['val_main']['base_rate']} (share of terminated trials in {years('val')}). "
        "Low: p < b; Medium: b ≤ p < 2b; High: p ≥ 2b.", "",
        *band_rows(r["bands_val"], r["band_cutoffs"]),
        "",
        "## 6. Feature importance", "",
        f"Permutation importance on validation: drop in PR-AUC when one feature is shuffled "
        f"(mean ± std over repeats). Near-zero or negative = the model doesn't rely on it.", "",
        "| Feature | PR-AUC drop | ± |", "|---|---|---|",
        *[f"| `{f['feature']}` | {f['pr_auc_drop_mean']} | {f['pr_auc_drop_std']} |"
          for f in r["feature_importance"][:20]],
        "",
        f"Logistic Regression ({r['logreg_coefficients']['params']}) largest coefficients on scaled inputs, "
        "as an easy-to-read reference (positive = more likely terminated):", "",
        "| Input | Coefficient |", "|---|---|",
        *[f"| `{t['input']}` | {t['coefficient']} |" for t in r["logreg_coefficients"]["top"]],
        "",
        "## 7. Every run", "",
        "| Data | Features | Model | Setting | PR-AUC | ROC-AUC | PR-AUC (with_covid val) | Fit s | Size MB |",
        "|---|---|---|---|---|---|---|---|---|",
        *[f"| {x['data_version']} | {x['feature_set']} | {x['model']} | {x['params']} | {x['val_main']['pr_auc']} | "
          f"{x['val_main']['roc_auc']} | {x['val_with_covid']['pr_auc']} | {x['fit_seconds']} | {x['size_mb']} |"
          for x in r["runs"]],
    ]
    return "\n".join(lines) + "\n"


def write_validation_report(report: dict, path: Path = VALIDATION_REPORT_MD) -> Path:
    """Write the validation report Markdown. Returns its path."""
    path.write_text(validation_markdown(report), encoding="utf-8")
    return path


def final_test_markdown(r: dict) -> str:
    """The one-time final test report as Markdown."""
    lines = [
        "# Final test report – Phase 9",
        "",
        f"Generated by `python -m src.model.final_test` on {r['generated_at']}. This was the **only** run on "
        f"the {years('test')} test set. Model file sha256 `{r['model_sha256']}`.",
        "",
        f"Model: `{r['model']}` (data `{r['data_version']}`, features `{r['feature_set']}`). Threshold "
        f"{r['threshold']} and risk bands were fixed on {years('val')} validation data before this run.",
        "",
    ]
    for key, title, note in (("test", f"Test set ({years('test')})", ""),
                             ("recent", f"Recent set ({years('recent')}), reported separately",
                              r["censoring_note"])):
        lines += [f"## {title}", ""]
        if note:
            lines += [note, ""]
        for version, part in r[key].items():
            lines += [f"### Rows: `{version}` ({part['rows']} trials, base rate {part['model']['base_rate']})", "",
                      *scores_rows([("Dummy (always completed)", part["dummy"]), (r["model"], part["model"])]),
                      "", *band_rows(part["bands"], r["band_cutoffs"]), ""]
    return "\n".join(lines) + "\n"


def write_final_test_report(report: dict, path: Path = FINAL_TEST_REPORT_MD) -> Path:
    """Write the final test report Markdown. Returns its path."""
    path.write_text(final_test_markdown(report), encoding="utf-8")
    return path
